DROP TABLE IF EXISTS `pdm_tool_cad_mock_test_log`;
DROP TABLE IF EXISTS `pdm_tool_cad_file_convert_task`;
DROP TABLE IF EXISTS `pdm_tool_cad_file_convert_config`;
DROP TABLE IF EXISTS `pdm_tool_cad_data_convert_mapping`;
DROP TABLE IF EXISTS `pdm_tool_cad_mock_interface`;

CREATE TABLE IF NOT EXISTS `pdm_tool_cad_mock_interface` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    `interface_name` VARCHAR(128) NOT NULL COMMENT '模拟接口名称',
    `cad_type` VARCHAR(32) NOT NULL COMMENT 'CAD类型',
    `convert_type` VARCHAR(32) NOT NULL DEFAULT 'DATA' COMMENT '转换类型',
    `apply_flow` VARCHAR(64) NOT NULL COMMENT '适用流程',
    `request_method` VARCHAR(16) NOT NULL DEFAULT 'POST' COMMENT '请求方式',
    `interface_url` VARCHAR(255) NOT NULL COMMENT '接口地址',
    `request_headers` LONGTEXT COMMENT '请求头JSON',
    `request_params` LONGTEXT COMMENT '请求参数JSON',
    `request_body_template` LONGTEXT COMMENT '请求体模板JSON',
    `response_body` LONGTEXT NOT NULL COMMENT '模拟响应内容JSON',
    `success_field` VARCHAR(64) DEFAULT 'code' COMMENT '成功标识字段',
    `success_value` VARCHAR(64) DEFAULT '200' COMMENT '成功标识值',
    `auth_type` VARCHAR(32) DEFAULT 'NONE' COMMENT '认证方式：NONE/BASIC/BEARER/API_KEY/CUSTOM_HEADERS',
    `auth_config` LONGTEXT COMMENT '认证配置JSON',
    `status` TINYINT DEFAULT 1 COMMENT '状态：0-停用，1-启用',
    `version_no` VARCHAR(32) DEFAULT 'V1.0' COMMENT '版本号',
    `owner_id` BIGINT COMMENT '负责人ID',
    `owner_name` VARCHAR(64) COMMENT '负责人名称',
    `remark` VARCHAR(500) COMMENT '备注',
    `create_id` BIGINT COMMENT '创建人',
    `create_name` VARCHAR(200) COMMENT '创建人名称',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_id` BIGINT COMMENT '更新人',
    `update_name` VARCHAR(200) COMMENT '更新人名称',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除：0-否，1-是',
    `deleted_by` BIGINT COMMENT '删除人',
    `deleted_time` DATETIME COMMENT '删除时间',
    INDEX `idx_cad_type_flow_status` (`cad_type`, `apply_flow`, `status`),
    INDEX `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CAD软件模拟接口配置表';

CREATE TABLE IF NOT EXISTS `pdm_tool_cad_data_convert_mapping` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    `mock_interface_id` BIGINT NOT NULL COMMENT '模拟接口ID',
    `cad_type` VARCHAR(32) NOT NULL COMMENT 'CAD类型',
    `apply_flow` VARCHAR(64) NOT NULL COMMENT '适用流程',
    `convert_direction` VARCHAR(32) NOT NULL DEFAULT 'RESPONSE' COMMENT '转换方向',
    `source_field` VARCHAR(128) NOT NULL COMMENT '源字段路径',
    `source_field_name` VARCHAR(128) COMMENT '源字段名称',
    `target_module` VARCHAR(64) NOT NULL COMMENT '目标模块',
    `target_field` VARCHAR(128) NOT NULL COMMENT '目标字段',
    `target_field_name` VARCHAR(128) COMMENT '目标字段名称',
    `field_type` VARCHAR(32) NOT NULL DEFAULT 'STRING' COMMENT '字段类型',
    `required` TINYINT DEFAULT 0 COMMENT '是否必填',
    `default_value` VARCHAR(255) COMMENT '默认值',
    `transform_rule` VARCHAR(500) COMMENT '转换规则',
    `sort_no` INT DEFAULT 0 COMMENT '排序号',
    `status` TINYINT DEFAULT 1 COMMENT '状态：0-停用，1-启用',
    `create_id` BIGINT COMMENT '创建人',
    `create_name` VARCHAR(200) COMMENT '创建人名称',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_id` BIGINT COMMENT '更新人',
    `update_name` VARCHAR(200) COMMENT '更新人名称',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除：0-否，1-是',
    `deleted_by` BIGINT COMMENT '删除人',
    `deleted_time` DATETIME COMMENT '删除时间',
    INDEX `idx_mock_interface_id` (`mock_interface_id`),
    INDEX `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CAD数据字段转换配置表';

CREATE TABLE IF NOT EXISTS `pdm_tool_cad_file_convert_config` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    `mock_interface_id` BIGINT COMMENT '模拟接口ID',
    `cad_type` VARCHAR(32) NOT NULL COMMENT 'CAD类型',
    `apply_flow` VARCHAR(64) NOT NULL COMMENT '适用流程',
    `source_format` VARCHAR(32) NOT NULL COMMENT '源文件格式',
    `target_format` VARCHAR(32) NOT NULL COMMENT '目标文件格式',
    `convert_url` VARCHAR(255) NOT NULL COMMENT '转换服务地址',
    `async_convert` TINYINT DEFAULT 1 COMMENT '是否异步转换',
    `timeout_seconds` INT DEFAULT 60 COMMENT '超时时间',
    `generate_preview` TINYINT DEFAULT 0 COMMENT '是否生成预览图',
    `keep_source_file` TINYINT DEFAULT 1 COMMENT '是否保留源文件',
    `overwrite_target_file` TINYINT DEFAULT 0 COMMENT '是否覆盖目标文件',
    `request_template` LONGTEXT COMMENT '转换请求模板JSON',
    `response_template` LONGTEXT COMMENT '转换响应模板JSON',
    `status` TINYINT DEFAULT 1 COMMENT '状态：0-停用，1-启用',
    `remark` VARCHAR(500) COMMENT '备注',
    `create_id` BIGINT COMMENT '创建人',
    `create_name` VARCHAR(200) COMMENT '创建人名称',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_id` BIGINT COMMENT '更新人',
    `update_name` VARCHAR(200) COMMENT '更新人名称',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除：0-否，1-是',
    `deleted_by` BIGINT COMMENT '删除人',
    `deleted_time` DATETIME COMMENT '删除时间',
    INDEX `idx_lookup` (`cad_type`, `apply_flow`, `source_format`, `target_format`, `status`),
    INDEX `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CAD文件格式转换配置表';

CREATE TABLE IF NOT EXISTS `pdm_tool_cad_file_convert_task` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    `task_no` VARCHAR(64) NOT NULL COMMENT '转换任务编号',
    `file_convert_config_id` BIGINT NOT NULL COMMENT '文件格式转换配置ID',
    `cad_type` VARCHAR(32) NOT NULL COMMENT 'CAD类型',
    `apply_flow` VARCHAR(64) NOT NULL COMMENT '适用流程',
    `source_file_id` BIGINT NOT NULL COMMENT '源文件ID',
    `source_file_name` VARCHAR(255) NOT NULL COMMENT '源文件名称',
    `source_format` VARCHAR(32) NOT NULL COMMENT '源文件格式',
    `target_file_id` BIGINT COMMENT '目标文件ID',
    `target_file_name` VARCHAR(255) COMMENT '目标文件名称',
    `target_format` VARCHAR(32) NOT NULL COMMENT '目标文件格式',
    `task_status` TINYINT NOT NULL DEFAULT 10 COMMENT '任务状态',
    `request_content` LONGTEXT COMMENT '请求内容JSON',
    `response_content` LONGTEXT COMMENT '响应内容JSON',
    `error_message` VARCHAR(1000) COMMENT '错误信息',
    `cost_time_ms` BIGINT COMMENT '耗时',
    `create_id` BIGINT COMMENT '创建人',
    `create_name` VARCHAR(200) COMMENT '创建人名称',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_id` BIGINT COMMENT '更新人',
    `update_name` VARCHAR(200) COMMENT '更新人名称',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除：0-否，1-是',
    `deleted_by` BIGINT COMMENT '删除人',
    `deleted_time` DATETIME COMMENT '删除时间',
    UNIQUE INDEX `uk_task_no` (`task_no`),
    INDEX `idx_config_id` (`file_convert_config_id`),
    INDEX `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CAD文件转换任务表';

CREATE TABLE IF NOT EXISTS `pdm_tool_cad_mock_test_log` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    `mock_interface_id` BIGINT NOT NULL COMMENT '模拟接口ID',
    `cad_type` VARCHAR(32) NOT NULL COMMENT 'CAD类型',
    `convert_type` VARCHAR(32) NOT NULL COMMENT '转换类型',
    `request_method` VARCHAR(16) NOT NULL COMMENT '请求方式',
    `interface_url` VARCHAR(255) NOT NULL COMMENT '接口地址',
    `request_content` LONGTEXT COMMENT '请求内容JSON',
    `response_content` LONGTEXT COMMENT '原始响应内容JSON',
    `converted_content` LONGTEXT COMMENT '转换后数据内容JSON',
    `file_convert_result` LONGTEXT COMMENT '文件转换结果JSON',
    `test_result` TINYINT NOT NULL COMMENT '测试结果：0-失败，1-成功',
    `error_message` VARCHAR(1000) COMMENT '错误信息',
    `cost_time_ms` BIGINT COMMENT '耗时',
    `create_id` BIGINT COMMENT '创建人',
    `create_name` VARCHAR(200) COMMENT '创建人名称',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_id` BIGINT COMMENT '更新人',
    `update_name` VARCHAR(200) COMMENT '更新人名称',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除：0-否，1-是',
    `deleted_by` BIGINT COMMENT '删除人',
    `deleted_time` DATETIME COMMENT '删除时间',
    INDEX `idx_mock_interface_id` (`mock_interface_id`),
    INDEX `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CAD模拟接口测试日志表';
